export const SPECIALTIES = [
  { name: 'General Medicine', icon: '🩺' },
  { name: 'Cardiology', icon: '❤️' },
  { name: 'Dermatology', icon: '🧴' },
  { name: 'Endocrinology', icon: '⏱️' },
  { name: 'Gastroenterology', icon: '🌡️' },
  { name: 'Neurology', icon: '🧠' },
  { name: 'Obstetrics & Gynecology', icon: '🌸' },
  { name: 'Oncology', icon: '🎯' },
  { name: 'Ophthalmology', icon: '👁️' },
  { name: 'Orthopedics', icon: '🦴' },
  { name: 'Pediatrics', icon: '👶' },
  { name: 'Psychiatry', icon: '🧠' },
  { name: 'Pulmonology', icon: '💨' },
  { name: 'Radiology', icon: '🩻' },
  { name: 'Urology', icon: '🔬' },
  { name: 'Other', icon: '🔎' },
]
